# -*- coding: utf-8 -*-
"""ev deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGBztwi8d_dZyamQVX4BMF6m4tIIxhOS
"""

import streamlit as st
import pandas as pd
import joblib

# Load the saved model and encoder
model_path = joblib.load('battery_encoder.joblib')
label_path= joblib.load('label_encoder.joblib')

st.title("EV Battery Safety Predictor")
st.markdown("Enter battery details below to assess the risk of failure.")

# User Inputs
col1, col2 = st.columns(2)

with col1:
    battery_type = st.selectbox("Battery Type", ["Lead-Acid", "Lithium-Ion"])
    poor_cell_design = st.radio("Poor Cell Design?", [0, 1], help="0 for No, 1 for Yes")
    external_abuse = st.selectbox("External Abuse?", ["Yes", "No"])
    poor_battery_design = st.radio("Poor Battery Design?", [0, 1])

with col2:
    short_circuits = st.radio("Short Circuits Recorded?", [0, 1])
    temperature = st.number_input("Current Temperature (°C)", min_value=0.0, max_value=100.0, value=35.0)
    overcharge = st.selectbox("Charging State", ["Normal", "Overcharge", "Over-discharge"])
    maintenance = st.selectbox("Proper Maintenance?", ["Yes", "No"])

if st.button("Predict Battery Health"):
    # Create DataFrame for prediction
    input_df = pd.DataFrame([{
        'Battery_Type': battery_type,
        'Poor_Cell_Design': poor_cell_design,
        'External_Abuse': external_abuse,
        'Poor_Battery_Design': poor_battery_design,
        'Short_Circuits': short_circuits,
        'Temperature': temperature,
        'Overcharge_Overdischarge': overcharge,
        'Battery_Maintenance': maintenance
    }])

    # Prediction
    prediction_idx = model.predict(input_df)[0]
    prediction_label = le.inverse_transform([prediction_idx])[0]
    probabilities = model.predict_proba(input_df)[0]

    # Output Result
    if prediction_label in ["Blast", "Chance_of_Blast"]:
        st.error(f"⚠️ Warning: {prediction_label.replace('_', ' ').upper()}")
    elif prediction_label == "Moderate":
        st.warning(f"Status: {prediction_label}")
    else:
        st.success(f"Status: {prediction_label}")

    st.write("Confidence Metrics:")
    st.bar_chart(pd.Series(probabilities, index=le.classes_))
